### ISSUE TITLE
有更简单更好的实现

### ISSUE THREAD

**Issue by ShenHongFei** [SynRGB/BiliBili-EasyCopy#2]
```typescript
document.querySelectorAll<HTMLDivElement>('#article-content').forEach($div => {
    $div.addEventListener(
        'copy', 
        event => { event.stopImmediatePropagation() }, 
        true
    )
})
```

**Comment by Mehver** [comment]
学习了！大佬愿意给个PR吗 @ShenHongFei ？谢谢！

**Comment by Mehver** [comment]
大大 @ShenHongFei 您不理我，我用 GitHub 的 `Co-authored-by` 功能直接把您 sign 到参考了您代码的 commit 上了。

另外想请教一下，我记得几个月前试您的代码时能直接用，但是今天想起来再试的时候，我这个新装的 Chrome 下，就报错了。

![image](https://github.com/user-attachments/assets/e6077001-ef55-480a-aa65-a8a4663fe43c)

GPT 说是语法兼容性问题，所以后续我也只是参考了您用的 `stopImmediatePropagation()` 和 `true`。我对 JS 和前端的理解都不深，我这种写法的兼容性怎么样？

https://github.com/SynRGB/BiliBili-EasyCopy/blob/04c9fa4d8192c409f80d77bd0d840b4565839835/BiliBili-EasyCopy.user.js#L21-L31

**Comment by ShenHongFei** [comment]
好的没问题的，代码直接用就行，在控制台里执行的时候把 `<HTMLDivElement>` 这个 typescript 类型注解去掉，就不会报错了

**Comment by Mehver** [comment]
哦哦，原来是 typescript 的类型注释😂，学习了！
